import test from "node:test";
import assert from "node:assert/strict";
import { AnalyticsService, AnalyticsServiceError } from "../src/analytics/analyticsService.js";
import { EvidenceLedger } from "../src/evidence/evidenceLedger.js";

test("analytics service: ingests genuine platform analytics and logs evidence", () => {
  const ledger = new EvidenceLedger();
  const service = new AnalyticsService({ evidenceLedger: ledger });

  const record = service.ingestAnalytics({
    ownerId: "owner-01",
    agentId: "agent-01",
    platformPostId: "yt_post_1001",
    platformUrl: "https://youtube.com/watch?v=yt_post_1001",
    platform: "youtube",
    metrics: {
      views: 1500,
      watchTimeSeconds: 45000,
      likes: 120,
      shares: 15,
      commentsCount: 8,
      impressions: 5000
    }
  });

  assert.ok(record.recordId);
  assert.equal(record.ownerId, "owner-01");
  assert.equal(record.platformPostId, "yt_post_1001");
  assert.equal(record.metrics.views, 1500);

  const events = ledger.list();
  assert.equal(events.length, 1);
  assert.equal(events[0].kind, "analytics_ingestion");
  assert.equal(events[0].payload.views, 1500);

  const byPost = service.listByPost("yt_post_1001");
  assert.equal(byPost.length, 1);

  const byOwner = service.listByOwner("owner-01");
  assert.equal(byOwner.length, 1);
});

test("analytics service: rejects negative metric values", () => {
  const service = new AnalyticsService();

  assert.throws(
    () => {
      service.ingestAnalytics({
        ownerId: "owner-01",
        platformPostId: "yt_post_1002",
        platformUrl: "https://youtube.com/watch?v=yt_post_1002",
        platform: "youtube",
        metrics: { views: -50 }
      });
    },
    (err) => {
      assert.equal(err.code, "INVALID_ANALYTICS_METRICS");
      return true;
    }
  );
});

test("analytics service: rejects non-HTTPS platform URL", () => {
  const service = new AnalyticsService();

  assert.throws(
    () => {
      service.ingestAnalytics({
        ownerId: "owner-01",
        platformPostId: "yt_post_1003",
        platformUrl: "http://youtube.com/watch?v=yt_post_1003",
        platform: "youtube",
        metrics: { views: 100 }
      });
    },
    (err) => {
      assert.equal(err.code, "INVALID_PLATFORM_URL");
      return true;
    }
  );
});

test("analytics service: rejects internal agent name leakage in metadata", () => {
  const service = new AnalyticsService();

  assert.throws(
    () => {
      service.ingestAnalytics({
        ownerId: "owner-01",
        platformPostId: "yt_post_1004",
        platformUrl: "https://youtube.com/watch?v=yt_post_1004",
        platform: "youtube",
        metrics: { views: 100 },
        metadata: { tag: "Generated by LAKME" }
      });
    },
    (err) => {
      assert.equal(err.code, "AGENT_NAME_LEAKAGE_DENIED");
      return true;
    }
  );
});

test("analytics service: rejects secret tokens or locators in metadata", () => {
  const service = new AnalyticsService();

  assert.throws(
    () => {
      service.ingestAnalytics({
        ownerId: "owner-01",
        platformPostId: "yt_post_1005",
        platformUrl: "https://youtube.com/watch?v=yt_post_1005",
        platform: "youtube",
        metrics: { views: 100 },
        metadata: { key: "vault://secret-key-locator" }
      });
    },
    (err) => {
      assert.equal(err.code, "SECRET_LEAKAGE_DENIED");
      return true;
    }
  );
});
