import test from "node:test";
import assert from "node:assert/strict";
import { WorkEnvelope, WorkEnvelopeValidationError, SecurityViolationError } from "../src/workers/workEnvelope.js";
import { WorkerRuntime, WorkerCancelledError, sanitizeError } from "../src/workers/workerRuntime.js";
import { CheckpointStore } from "../src/checkpoints/checkpointStore.js";

// Explicitly named test adapter to meet CheckpointStore constructor requirements
class TestCheckpointAdapter {
  constructor() {
    this.name = "TestCheckpointAdapter";
    this.store = new Map();
  }
  async get(key) {
    return this.store.get(key) || null;
  }
  async set(key, value) {
    this.store.set(key, value);
  }
}

// Explicitly named test store to meet WorkerRuntime constructor requirements
class TestIdempotencyStore {
  constructor() {
    this.name = "TestIdempotencyStore";
    this.store = new Map();
  }
  async get(key) {
    return this.store.get(key) || null;
  }
  async set(key, value) {
    this.store.set(key, value);
  }
}

test("WorkerRuntime - validates constructor parameters and production safety", () => {
  // Fail production construction closed if missing adapter/store
  assert.throws(
    () => new WorkerRuntime({ isTestEnv: false }),
    /WorkerRuntime requires a durable state\/idempotency store/
  );

  // Fail production construction closed if in-memory fallback is provided
  const fakeInMemoryProductionStore = {
    get: async () => null,
    set: async () => {},
    isInMemory: true
  };
  assert.throws(
    () => new WorkerRuntime({ idempotencyStore: fakeInMemoryProductionStore, isTestEnv: false }),
    /Silent in-memory idempotency fallbacks are prohibited/
  );

  // Validate store interface
  assert.throws(
    () => new WorkerRuntime({ idempotencyStore: { get: () => {} }, isTestEnv: false }),
    /Invalid idempotency store interface/
  );

  // Works with test environment option
  const testRuntime = new WorkerRuntime({ isTestEnv: true });
  assert.ok(testRuntime);
});

test("WorkEnvelope - validates required fields and types", () => {
  // Empty data
  assert.throws(() => new WorkEnvelope(null), WorkEnvelopeValidationError);

  // Missing taskId
  assert.throws(() => new WorkEnvelope({
    jobType: "render",
    agentId: "agent-01",
    payload: {},
    context: {}
  }), WorkEnvelopeValidationError);

  // Missing jobType
  assert.throws(() => new WorkEnvelope({
    taskId: "task-1",
    agentId: "agent-01",
    payload: {},
    context: {}
  }), WorkEnvelopeValidationError);

  // Missing agentId
  assert.throws(() => new WorkEnvelope({
    taskId: "task-1",
    jobType: "render",
    payload: {},
    context: {}
  }), WorkEnvelopeValidationError);

  // Correct instantiation
  const envelope = new WorkEnvelope({
    taskId: "task-1",
    jobType: "render",
    agentId: "agent-01",
    payload: { inputVideo: "raw.mp4" },
    context: { isProduction: true }
  });

  assert.equal(envelope.taskId, "task-1");
  assert.equal(envelope.jobType, "render");
  assert.equal(envelope.agentId, "agent-01");
  assert.deepEqual(envelope.payload, { inputVideo: "raw.mp4" });
  assert.deepEqual(envelope.context, { isProduction: true });
});

test("WorkEnvelope - rejects plaintext secrets but accepts opaque locators", () => {
  // Reject plaintext api_key
  assert.throws(() => new WorkEnvelope({
    taskId: "task-1",
    jobType: "render",
    agentId: "agent-01",
    payload: { apiKey: "secret_12345" },
    context: {}
  }), SecurityViolationError);

  // Reject password in context
  assert.throws(() => new WorkEnvelope({
    taskId: "task-1",
    jobType: "render",
    agentId: "agent-01",
    payload: {},
    context: { dbPassword: "supersecretpassword" }
  }), SecurityViolationError);

  // Accept opaque locator (vault://)
  const okEnvelope = new WorkEnvelope({
    taskId: "task-1",
    jobType: "render",
    agentId: "agent-01",
    payload: { apiKey: "vault://secret-manager/api-key" },
    context: { dbPassword: "opaque://database-credentials/password" }
  });

  assert.equal(okEnvelope.payload.apiKey, "vault://secret-manager/api-key");
  assert.equal(okEnvelope.context.dbPassword, "opaque://database-credentials/password");
});

test("WorkEnvelope - rejects public fields with internal agent names", () => {
  // JARVIS is a preloaded internal agent name, so it should be blocked from public fields
  assert.throws(() => new WorkEnvelope({
    taskId: "task-1",
    jobType: "render",
    agentId: "agent-01",
    payload: {
      videoCaption: "This amazing post was generated by JARVIS."
    },
    context: {}
  }), SecurityViolationError);

  // VEDA is blocked too
  assert.throws(() => new WorkEnvelope({
    taskId: "task-1",
    jobType: "render",
    agentId: "agent-01",
    payload: {
      publicBrandName: "VEDA Studios"
    },
    context: {}
  }), SecurityViolationError);

  // Normal, non-internal agent name is fine
  const normal = new WorkEnvelope({
    taskId: "task-1",
    jobType: "render",
    agentId: "agent-01",
    payload: {
      videoCaption: "This amazing post was generated by a super creative tool."
    },
    context: {}
  });
  assert.ok(normal);
});

test("WorkerRuntime - successfully runs a handler and returns HandlerResult", async () => {
  const runtime = new WorkerRuntime({ isTestEnv: true });
  const envelope = {
    taskId: "task-success-1",
    jobType: "render",
    agentId: "agent-01",
    payload: { src: "input.mov" },
    context: {}
  };

  const result = await runtime.run(envelope, async (ctx) => {
    ctx.addArtifact({ path: "rendered.mp4", sha256: "renderhash1", type: "video" });
    ctx.addEvidence("ev-999");
    return { status: "processed", outPath: "rendered.mp4" };
  });

  assert.equal(result.taskId, "task-success-1");
  assert.equal(result.status, "success");
  assert.deepEqual(result.output, { status: "processed", outPath: "rendered.mp4" });
  assert.equal(result.artifactRefs[0].path, "rendered.mp4");
  assert.equal(result.evidenceRefs[0], "ev-999");
  assert.ok(result.durationMs >= 0);
  assert.ok(result.completedAt);
});

test("WorkerRuntime - handles heartbeats and checkpointing during execution", async () => {
  const runtime = new WorkerRuntime({ isTestEnv: true });
  const checkpointStore = new CheckpointStore(new TestCheckpointAdapter());
  const heartbeats = [];

  const envelope = {
    taskId: "task-hb-cp",
    jobType: "transcode",
    agentId: "agent-01",
    payload: { video: "clip.avi" },
    context: {}
  };

  const result = await runtime.run(envelope, async (ctx) => {
    ctx.heartbeat("started", 10, { memory: "128MB" });

    await ctx.checkpoint("step-1", 50, { frame: 500 }, [
      { path: "frame500.png", sha256: "f500hash", type: "image" }
    ], ["evidence-step-1"]);

    ctx.heartbeat("halfway", 60, { memory: "150MB" });

    return { done: true };
  }, {
    checkpointStore,
    onHeartbeat: (hb) => {
      heartbeats.push(hb);
    }
  });

  assert.equal(result.status, "success");

  // Validate heartbeats
  assert.equal(heartbeats.length, 2);
  assert.equal(heartbeats[0].step, "started");
  assert.equal(heartbeats[0].progress, 10);
  assert.deepEqual(heartbeats[0].metrics, { memory: "128MB" });

  // Validate checkpoints
  const checkpoint = await checkpointStore.read("task-hb-cp");
  assert.equal(checkpoint.step, "step-1");
  assert.equal(checkpoint.progress, 50);
  assert.deepEqual(checkpoint.data, { frame: 500 });
  assert.equal(checkpoint.artifactRefs[0].path, "frame500.png");
  assert.equal(checkpoint.evidenceRefs[0], "evidence-step-1");
});

test("WorkerRuntime - supports cooperative cancellation and fails closed", async () => {
  const runtime = new WorkerRuntime({ isTestEnv: true });
  const controller = new AbortController();

  const envelope = {
    taskId: "task-cancelled",
    jobType: "render",
    agentId: "agent-02",
    payload: {},
    context: {}
  };

  const resultPromise = runtime.run(envelope, async (ctx) => {
    ctx.checkCancellation();
    controller.abort(); // Cancel while running
    ctx.checkCancellation(); // Should throw here
    return { value: "not-reached" };
  }, { signal: controller.signal });

  const result = await resultPromise;

  assert.equal(result.status, "cancelled");
  assert.equal(result.error.name, "WorkerCancelledError");
  assert.equal(result.failClosed, true);
  assert.ok(result.cancelledAt);
});

test("WorkerRuntime - enforces idempotent completion in the durable state store", async () => {
  const idempotencyStore = new TestIdempotencyStore();
  const runtime = new WorkerRuntime({ idempotencyStore, isTestEnv: true });
  let executionCount = 0;

  const envelope = {
    taskId: "task-idempotent-run",
    jobType: "upload",
    agentId: "agent-01",
    payload: {},
    context: {}
  };

  const handler = async () => {
    executionCount++;
    return { uploadId: "up-777" };
  };

  // Run first time
  const r1 = await runtime.run(envelope, handler);
  // Run second time (should pull from idempotencyStore without re-executing)
  const r2 = await runtime.run(envelope, handler);

  assert.equal(executionCount, 1); // Handler must only run once!
  assert.deepEqual(r1, r2);
  assert.equal(r1.status, "success");

  // Durability verification: spin up a NEW runtime referencing the SAME store, verify it returns same cached result
  const runtimeB = new WorkerRuntime({ idempotencyStore, isTestEnv: true });
  const r3 = await runtimeB.run(envelope, handler);
  assert.deepEqual(r1, r3);
  assert.equal(executionCount, 1);
});

test("WorkerRuntime - fails closed on handler failure, sanitizing error details", async () => {
  const runtime = new WorkerRuntime({ isTestEnv: true });
  const envelope = {
    taskId: "task-failing",
    jobType: "transcode",
    agentId: "agent-01",
    payload: {},
    context: {}
  };

  const result = await runtime.run(envelope, async () => {
    throw new Error("Critical transcode database issue. Secret password was vault://secrets/db-pass");
  });

  assert.equal(result.status, "failed");
  assert.equal(result.failClosed, true);
  assert.ok(!result.error.message.includes("vault://secrets/db-pass"));
  assert.ok(result.error.message.includes("[REDACTED_SECRET]"));
  assert.ok(result.failedAt);
});

test("WorkerRuntime - does not swallow heartbeat callback failures", async () => {
  const runtime = new WorkerRuntime({ isTestEnv: true });
  const envelope = {
    taskId: "task-hb-failure",
    jobType: "publish",
    agentId: "agent-01",
    payload: {},
    context: {}
  };

  // Run with heartbeat callback that throws error
  const result = await runtime.run(
    envelope,
    async (ctx) => {
      ctx.heartbeat("step-1", 10);
      return { success: true };
    },
    {
      onHeartbeat: () => {
        throw new Error("Telemetry connection lost!");
      }
    }
  );

  // The worker must fail closed due to heartbeat callback error propagation
  assert.equal(result.status, "failed");
  assert.equal(result.failClosed, true);
  assert.equal(result.error.message, "Telemetry connection lost!");
});

test("WorkerRuntime - advanced secret redactions on error message and stack trace publicly", () => {
  const rawErrors = [
    new Error("Database connection postgres://admin:superSecretPassword@db.host.com:5432/main failed"),
    new Error("Failed authorizing Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"),
    new Error("Unauthorized request. Cookie: session=998822ab123; userId=9"),
    new Error("API key invalid: apikey=mySecretKey123"),
    new Error("Cannot write file with privatekey:ssh-rsa-AAAAB3Nza")
  ];

  for (const err of rawErrors) {
    const sanitized = sanitizeError(err);
    assert.equal(sanitized.stack, "[REDACTED_STACK_TRACE]");
    assert.ok(!sanitized.message.includes("superSecretPassword"));
    assert.ok(!sanitized.message.includes("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"));
    assert.ok(!sanitized.message.includes("998822ab123"));
    assert.ok(!sanitized.message.includes("mySecretKey123"));
    assert.ok(!sanitized.message.includes("ssh-rsa-AAAAB3Nza"));
  }
});
